version: '3.8'

services:
  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./:/app
  #   tty: true

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./frontend:/app
  #     - node_modules:/app/node_modules
  #   tty: true
  
  redis:
    image: redis/redis-stack
    ports:
      - 6379:6379
    # volumes:
    #   - ./redis:/data

# volumes:
#   node_modules:
