version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    tty: true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    command: yarn dev
    tty: true

  nginx:
    build: ./nginx
    ports:
      - 3000:3000
    depends_on:
      - backend
      - frontend

volumes:
  node_modules:
