services:
  mongo:
    image: mongo:8.0.0-rc20
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    tty: true
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s

volumes:
  mongodata:
