services:
  mongo:
    image: mongo:8.0
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
      - ./docker/mongo/init-replica.sh:/docker-entrypoint-initdb.d/init-replica.sh
    tty: true
    command: ["mongod", "--replSet", "myReplicaSet"]
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s

volumes:
  mongodata:
