version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    tty: true

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front:/app
      - node_modules:/app/node_modules
    command: yarn dev
    tty: true

  nginx:
    build: ./nginx
    ports:
      - 3000:3000
    depends_on:
      - api
      - front

volumes:
  node_modules:
