version: '3.8'

services:
  neo4j:
    image: neo4j
    ports: 
      - 7474:7474
      - 7687:7687
    volumes: 
      - ./neo4j/data:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./:/workspace
    env_file:
      - ./backend/.env
    tty: true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    command: yarn dev
    tty: true

  nginx:
    build: ./nginx
    ports:
      - 3000:3000
    depends_on:
      - backend
      - frontend

volumes:
  # https://zenn.dev/philomagi/scraps/d16d73d2f9d6f9
  node_modules:
    driver: local
    driver_opts:
      type: none
      device: ./frontend/node_modules
      o: bind
