services:
  mongo:
    image: mongo:8.0.0-rc20
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    tty: true
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s

volumes:
  mongodata:
