# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  dev:
    watch: true
    cmds:
      - cmd: kill $(lsof -t -i:3000)
        ignore_error: true
      - cd frontend && pnpm build 
      - go run . up
    sources:
      - ./frontend/src/**/*
    generates:
      - ./frontend/dist/**/*
