openapi: 3.0.3
info:
  version: 0.1.0
  title: Example
  description: Example
servers:
  - url: http://localhost:3000/api
paths:
  /books/list:
    get:
      summary: list books
      operationId: getBooksList
      parameters:
      responses:
        '200':
          description: pet response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BooksList'
components:
  schemas:
    BooksList:
      additionalProperties: false
      required:
        - message
      properties:
        message:
          type: string
          description: Message
