name: fmt

on:
  schedule:
    - cron: '0 12 * * 3'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  fmt:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v3
        with:
          go-version: '1.22'
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - uses: pnpm/action-setup@v2
        with:
          version: '8'

      - working-directory: ui
        run: pnpm install
      - working-directory: ui
        run: pnpm format

      - run: go generate ./...
      - run: go fmt ./...

      - uses: peter-evans/create-pull-request@v6
        with:
          commit-message: |
            chore(fmt): fmt

            run `pnpm format`
            run `go fmt ./...`
          delete-branch: true
          title: '[bot] fmt'
          body: 'format code on github actions. Please look at file changes.'
          reviewers: enuesaa
          author: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
          branch: fmt
          branch-suffix: timestamp
